[package]
name = "brainfuck"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "jump"
path = "src/main_jump.rs"

[[bin]]
name = "recursive"
path = "src/main_recursive.rs"

[[bin]]
name = "without_parser"
path = "src/main_without_parser.rs"
